[project]
name = "fluorite-gcp-cli"
version = "0.1.0"
description = "Tool to create a Fluorite cluster on GCP"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "requests==2.32.5",
    "pydantic==2.12.5",
]

[project.scripts]
fluorite-gcp = "main:cli"
