# Resources
# - https://doc.traefik.io/traefik/user-guides/crd-acme/
# - https://doc.traefik.io/traefik/user-guides/cert-manager/
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-deployment
  labels:
    app: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-ingress-controller
      containers:
        - name: traefik
          image: traefik:v3.6.6
          args:
            - --entryPoints.web.address=:80
            - --entryPoints.websecure.address=:443
            - --providers.kubernetescrd
            - --providers.kubernetesingress # For the Ingress created by cert-manager
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-service

spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: websecure
      port: 443
    - protocol: TCP
      name: web
      port: 80
  selector:
    app: traefik
---
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: tlsoptions
spec:
  sniStrict: true
  # Modern ciphersuites recommended by Cloudflare:
  # https://developers.cloudflare.com/ssl/edge-certificates/additional-options/cipher-suites/recommendations/#modern
  cipherSuites:
    - TLS_AES_128_GCM_SHA256                        # 0x1301, TLS 1.3
    - TLS_AES_256_GCM_SHA384                        # 0x1302, TLS 1.3
    - TLS_CHACHA20_POLY1305_SHA256                  # 0x1303, TLS 1.3
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256       # 0xc02b, TLS 1.2
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 # 0xcca9, TLS 1.2
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384       # 0xc02c, TLS 1.2
    - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256         # 0xc02f, TLS 1.2
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256   # 0xcca8, TLS 1.2
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384         # 0xc030, TLS 1.2
  minVersion: VersionTLS12
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: traefik
spec:
  controller: traefik.io/ingress-controller
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: security-headers-middleware
  
spec:
  headers:
    stsPreload: true
    stsSeconds: 31536000
    forceSTSHeader: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-https-middleware
  
spec:
  redirectScheme:
    scheme: https
    permanent: true