apiVersion: v1
kind: Secret
metadata:
  name: plugin-secrets
  namespace: cert-manager
type: Opaque
data:
  attestation: ###ZARF_VAR_ATTESTATION_B64###
  signature-private-key: ###ZARF_VAR_SIGNATURE_PRIVATE_KEY_B64###
immutable: true
